<?php

use App\Models\City;
use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        City::create(['name' => 'Leticia', 'department_id' => 1]);
        City::create(['name' => 'El encanto', 'department_id' => 1]);
        City::create(['name' => 'La chorrera', 'department_id' => 1]);
        City::create(['name' => 'La pedrera', 'department_id' => 1]);
        City::create(['name' => 'La victoria', 'department_id' => 1]);
        City::create(['name' => 'Miriti - parana', 'department_id' => 1]);
        City::create(['name' => 'Puerto alegria', 'department_id' => 1]);
        City::create(['name' => 'Puerto arica', 'department_id' => 1]);
        City::create(['name' => 'Puerto nariño', 'department_id' => 1]);
        City::create(['name' => 'Puerto santander', 'department_id' => 1]);
        City::create(['name' => 'Tarapaca', 'department_id' => 1]);

        City::create(['name' => 'Medellín', 'department_id' => 2]);
        City::create(['name' => 'Abejorral', 'department_id' => 2]);
        City::create(['name' => 'Abriaquí', 'department_id' => 2]);
        City::create(['name' => 'Alejandría', 'department_id' => 2]);
        City::create(['name' => 'Amagá', 'department_id' => 2]);
        City::create(['name' => 'Amalfi', 'department_id' => 2]);
        City::create(['name' => 'Andes', 'department_id' => 2]);
        City::create(['name' => 'Angelópolis', 'department_id' => 2]);
        City::create(['name' => 'Angostura', 'department_id' => 2]);
        City::create(['name' => 'Anori', 'department_id' => 2]);
        City::create(['name' => 'Santafe de antioquia', 'department_id' => 2]);
        City::create(['name' => 'Anza', 'department_id' => 2]);
        City::create(['name' => 'Apartadó', 'department_id' => 2]);
        City::create(['name' => 'Arboletes', 'department_id' => 2]);
        City::create(['name' => 'Argelia', 'department_id' => 2]);
        City::create(['name' => 'Armenia', 'department_id' => 2]);
        City::create(['name' => 'Barbosa', 'department_id' => 2]);
        City::create(['name' => 'Belmira', 'department_id' => 2]);
        City::create(['name' => 'Bello', 'department_id' => 2]);
        City::create(['name' => 'Betania', 'department_id' => 2]);
        City::create(['name' => 'Betulia', 'department_id' => 2]);
        City::create(['name' => 'Ciudad bolivar', 'department_id' => 2]);
        City::create(['name' => 'Briceño', 'department_id' => 2]);
        City::create(['name' => 'Buritica', 'department_id' => 2]);
        City::create(['name' => 'Caceres', 'department_id' => 2]);
        City::create(['name' => 'Caicedo', 'department_id' => 2]);
        City::create(['name' => 'Caldas', 'department_id' => 2]);
        City::create(['name' => 'Campamento', 'department_id' => 2]);
        City::create(['name' => 'Cañasgordas', 'department_id' => 2]);
        City::create(['name' => 'Caracoli', 'department_id' => 2]);
        City::create(['name' => 'Caramanta', 'department_id' => 2]);
        City::create(['name' => 'Carepa', 'department_id' => 2]);
        City::create(['name' => 'El carmen de viboral', 'department_id' => 2]);
        City::create(['name' => 'Carolina', 'department_id' => 2]);
        City::create(['name' => 'Caucasia', 'department_id' => 2]);
        City::create(['name' => 'Chigorodo', 'department_id' => 2]);
        City::create(['name' => 'Cisneros', 'department_id' => 2]);
        City::create(['name' => 'Cocorna', 'department_id' => 2]);
        City::create(['name' => 'Concepcion', 'department_id' => 2]);
        City::create(['name' => 'Concordia', 'department_id' => 2]);
        City::create(['name' => 'Copacabana', 'department_id' => 2]);
        City::create(['name' => 'Dabeiba', 'department_id' => 2]);
        City::create(['name' => 'Don matias', 'department_id' => 2]);
        City::create(['name' => 'Ebejico', 'department_id' => 2]);
        City::create(['name' => 'El bagre', 'department_id' => 2]);
        City::create(['name' => 'Entrerrios', 'department_id' => 2]);
        City::create(['name' => 'Envigado', 'department_id' => 2]);
        City::create(['name' => 'Fredonia', 'department_id' => 2]);
        City::create(['name' => 'Frontino', 'department_id' => 2]);
        City::create(['name' => 'Giraldo', 'department_id' => 2]);
        City::create(['name' => 'Girardota', 'department_id' => 2]);
        City::create(['name' => 'Gomez plata', 'department_id' => 2]);
        City::create(['name' => 'Granada', 'department_id' => 2]);
        City::create(['name' => 'Guadalupe', 'department_id' => 2]);
        City::create(['name' => 'Guarne', 'department_id' => 2]);
        City::create(['name' => 'Guatape', 'department_id' => 2]);
        City::create(['name' => 'Heliconia', 'department_id' => 2]);
        City::create(['name' => 'Hispania', 'department_id' => 2]);
        City::create(['name' => 'Itagui', 'department_id' => 2]);
        City::create(['name' => 'Ituango', 'department_id' => 2]);
        City::create(['name' => 'Jardin', 'department_id' => 2]);
        City::create(['name' => 'Jerico', 'department_id' => 2]);
        City::create(['name' => 'La ceja', 'department_id' => 2]);
        City::create(['name' => 'La estrella', 'department_id' => 2]);
        City::create(['name' => 'La pintada', 'department_id' => 2]);
        City::create(['name' => 'La union', 'department_id' => 2]);
        City::create(['name' => 'Liborina', 'department_id' => 2]);
        City::create(['name' => 'Maceo', 'department_id' => 2]);
        City::create(['name' => 'Marinilla', 'department_id' => 2]);
        City::create(['name' => 'Montebello', 'department_id' => 2]);
        City::create(['name' => 'Murindo', 'department_id' => 2]);
        City::create(['name' => 'Mutata', 'department_id' => 2]);
        City::create(['name' => 'Nariño', 'department_id' => 2]);
        City::create(['name' => 'Necocli', 'department_id' => 2]);
        City::create(['name' => 'Nechi', 'department_id' => 2]);
        City::create(['name' => 'Olaya', 'department_id' => 2]);
        City::create(['name' => 'Peðol', 'department_id' => 2]);
        City::create(['name' => 'Peque', 'department_id' => 2]);
        City::create(['name' => 'Pueblorrico', 'department_id' => 2]);
        City::create(['name' => 'Puerto berrio', 'department_id' => 2]);
        City::create(['name' => 'Puerto nare', 'department_id' => 2]);
        City::create(['name' => 'Puerto triunfo', 'department_id' => 2]);
        City::create(['name' => 'Remedios', 'department_id' => 2]);
        City::create(['name' => 'Retiro', 'department_id' => 2]);
        City::create(['name' => 'Rionegro', 'department_id' => 2]);
        City::create(['name' => 'Sabanalarga', 'department_id' => 2]);
        City::create(['name' => 'Sabaneta', 'department_id' => 2]);
        City::create(['name' => 'Salgar', 'department_id' => 2]);
        City::create(['name' => 'San andres de cuerquia', 'department_id' => 2]);
        City::create(['name' => 'San carlos', 'department_id' => 2]);
        City::create(['name' => 'San francisco', 'department_id' => 2]);
        City::create(['name' => 'San jeronimo', 'department_id' => 2]);
        City::create(['name' => 'San jose de la montaña', 'department_id' => 2]);
        City::create(['name' => 'San juan de uraba', 'department_id' => 2]);
        City::create(['name' => 'San luis', 'department_id' => 2]);
        City::create(['name' => 'San pedro', 'department_id' => 2]);
        City::create(['name' => 'San pedro de uraba', 'department_id' => 2]);
        City::create(['name' => 'San rafael', 'department_id' => 2]);
        City::create(['name' => 'San roque', 'department_id' => 2]);
        City::create(['name' => 'San vicente', 'department_id' => 2]);
        City::create(['name' => 'Santa barbara', 'department_id' => 2]);
        City::create(['name' => 'Santa rosa de osos', 'department_id' => 2]);
        City::create(['name' => 'Santo domingo', 'department_id' => 2]);
        City::create(['name' => 'El santuario', 'department_id' => 2]);
        City::create(['name' => 'Segovia', 'department_id' => 2]);
        City::create(['name' => 'Sonson', 'department_id' => 2]);
        City::create(['name' => 'Sopetran', 'department_id' => 2]);
        City::create(['name' => 'Tamesis', 'department_id' => 2]);
        City::create(['name' => 'Taraza', 'department_id' => 2]);
        City::create(['name' => 'Tarso', 'department_id' => 2]);
        City::create(['name' => 'Titiribi', 'department_id' => 2]);
        City::create(['name' => 'Toledo', 'department_id' => 2]);
        City::create(['name' => 'Turbo', 'department_id' => 2]);
        City::create(['name' => 'Uramita', 'department_id' => 2]);
        City::create(['name' => 'Urrao', 'department_id' => 2]);
        City::create(['name' => 'Valdivia', 'department_id' => 2]);
        City::create(['name' => 'Valparaiso', 'department_id' => 2]);
        City::create(['name' => 'Vegachi', 'department_id' => 2]);
        City::create(['name' => 'Venecia', 'department_id' => 2]);
        City::create(['name' => 'Vigia del fuerte', 'department_id' => 2]);
        City::create(['name' => 'Yali', 'department_id' => 2]);
        City::create(['name' => 'Yarumal', 'department_id' => 2]);
        City::create(['name' => 'Yolombo', 'department_id' => 2]);
        City::create(['name' => 'Yondo', 'department_id' => 2]);
        City::create(['name' => 'Zaragoza', 'department_id' => 2]);

        City::create(['name' => 'Arauca', 'department_id' => 3]);
        City::create(['name' => 'Arauquita', 'department_id' => 3]);
        City::create(['name' => 'Cravo norte', 'department_id' => 3]);
        City::create(['name' => 'Fortul', 'department_id' => 3]);
        City::create(['name' => 'Puerto rondon', 'department_id' => 3]);
        City::create(['name' => 'Saravena', 'department_id' => 3]);
        City::create(['name' => 'Tame', 'department_id' => 3]);

        City::create(['name' => 'Barranquilla', 'department_id' => 4]);
        City::create(['name' => 'Baranoa', 'department_id' => 4]);
        City::create(['name' => 'Campo de la cruz', 'department_id' => 4]);
        City::create(['name' => 'Candelaria', 'department_id' => 4]);
        City::create(['name' => 'Galapa', 'department_id' => 4]);
        City::create(['name' => 'Juan de acosta', 'department_id' => 4]);
        City::create(['name' => 'Luruaco', 'department_id' => 4]);
        City::create(['name' => 'Malambo', 'department_id' => 4]);
        City::create(['name' => 'Manati', 'department_id' => 4]);
        City::create(['name' => 'Palmar de varela', 'department_id' => 4]);
        City::create(['name' => 'Piojo', 'department_id' => 4]);
        City::create(['name' => 'Polonuevo', 'department_id' => 4]);
        City::create(['name' => 'Ponedera', 'department_id' => 4]);
        City::create(['name' => 'Puerto colombia', 'department_id' => 4]);
        City::create(['name' => 'Repelon', 'department_id' => 4]);
        City::create(['name' => 'Sabanagrande', 'department_id' => 4]);
        City::create(['name' => 'Sabanalarga', 'department_id' => 4]);
        City::create(['name' => 'Santa lucia', 'department_id' => 4]);
        City::create(['name' => 'Santo tomas', 'department_id' => 4]);
        City::create(['name' => 'Soledad', 'department_id' => 4]);
        City::create(['name' => 'Suan', 'department_id' => 4]);
        City::create(['name' => 'Tubara', 'department_id' => 4]);
        City::create(['name' => 'Usiacuri', 'department_id' => 4]);

        City::create(['name' => 'Bogotá', 'department_id' => 5]);

        City::create(['name' => 'Cartagena', 'department_id' => 6]);
        City::create(['name' => 'Achi', 'department_id' => 6]);
        City::create(['name' => 'Altos del rosario', 'department_id' => 6]);
        City::create(['name' => 'Arenal', 'department_id' => 6]);
        City::create(['name' => 'Arjona', 'department_id' => 6]);
        City::create(['name' => 'Arroyohondo', 'department_id' => 6]);
        City::create(['name' => 'Barranco de loba', 'department_id' => 6]);
        City::create(['name' => 'Calamar', 'department_id' => 6]);
        City::create(['name' => 'Cantagallo', 'department_id' => 6]);
        City::create(['name' => 'Cicuco', 'department_id' => 6]);
        City::create(['name' => 'Cordoba', 'department_id' => 6]);
        City::create(['name' => 'Clemencia', 'department_id' => 6]);
        City::create(['name' => 'El carmen de bolivar', 'department_id' => 6]);
        City::create(['name' => 'El guamo', 'department_id' => 6]);
        City::create(['name' => 'El peñon', 'department_id' => 6]);
        City::create(['name' => 'Hatillo de loba', 'department_id' => 6]);
        City::create(['name' => 'Magangue', 'department_id' => 6]);
        City::create(['name' => 'Mahates', 'department_id' => 6]);
        City::create(['name' => 'Margarita', 'department_id' => 6]);
        City::create(['name' => 'Maria la baja', 'department_id' => 6]);
        City::create(['name' => 'Montecristo', 'department_id' => 6]);
        City::create(['name' => 'Mompos', 'department_id' => 6]);
        City::create(['name' => 'Norosi', 'department_id' => 6]);
        City::create(['name' => 'Morales', 'department_id' => 6]);
        City::create(['name' => 'Pinillos', 'department_id' => 6]);
        City::create(['name' => 'Regidor', 'department_id' => 6]);
        City::create(['name' => 'Rio viejo', 'department_id' => 6]);
        City::create(['name' => 'San cristobal', 'department_id' => 6]);
        City::create(['name' => 'San estanislao', 'department_id' => 6]);
        City::create(['name' => 'San fernando', 'department_id' => 6]);
        City::create(['name' => 'San jacinto', 'department_id' => 6]);
        City::create(['name' => 'San jacinto del cauca', 'department_id' => 6]);
        City::create(['name' => 'San juan nepomuceno', 'department_id' => 6]);
        City::create(['name' => 'San martin de loba', 'department_id' => 6]);
        City::create(['name' => 'San pablo', 'department_id' => 6]);
        City::create(['name' => 'Santa catalina', 'department_id' => 6]);
        City::create(['name' => 'Santa rosa', 'department_id' => 6]);
        City::create(['name' => 'Santa rosa del sur', 'department_id' => 6]);
        City::create(['name' => 'Simiti', 'department_id' => 6]);
        City::create(['name' => 'Soplaviento', 'department_id' => 6]);
        City::create(['name' => 'Talaigua nuevo', 'department_id' => 6]);
        City::create(['name' => 'Tiquisio', 'department_id' => 6]);
        City::create(['name' => 'Turbaco', 'department_id' => 6]);
        City::create(['name' => 'Turbana', 'department_id' => 6]);
        City::create(['name' => 'Villanueva', 'department_id' => 6]);
        City::create(['name' => 'Zambrano', 'department_id' => 6]);

        City::create(['name' => 'Tunja', 'department_id' => 7]);
        City::create(['name' => 'Almeida', 'department_id' => 7]);
        City::create(['name' => 'Aquitania', 'department_id' => 7]);
        City::create(['name' => 'Arcabuco', 'department_id' => 7]);
        City::create(['name' => 'Belen', 'department_id' => 7]);
        City::create(['name' => 'Berbeo', 'department_id' => 7]);
        City::create(['name' => 'Beteitiva', 'department_id' => 7]);
        City::create(['name' => 'Boavita', 'department_id' => 7]);
        City::create(['name' => 'Boyaca', 'department_id' => 7]);
        City::create(['name' => 'Briceño', 'department_id' => 7]);
        City::create(['name' => 'Buenavista', 'department_id' => 7]);
        City::create(['name' => 'Busbanza', 'department_id' => 7]);
        City::create(['name' => 'Caldas', 'department_id' => 7]);
        City::create(['name' => 'Campohermoso', 'department_id' => 7]);
        City::create(['name' => 'Cerinza', 'department_id' => 7]);
        City::create(['name' => 'Chinavita', 'department_id' => 7]);
        City::create(['name' => 'Chiquinquira', 'department_id' => 7]);
        City::create(['name' => 'Chiscas', 'department_id' => 7]);
        City::create(['name' => 'Chita', 'department_id' => 7]);
        City::create(['name' => 'Chitaraque', 'department_id' => 7]);
        City::create(['name' => 'Chivata', 'department_id' => 7]);
        City::create(['name' => 'Cienega', 'department_id' => 7]);
        City::create(['name' => 'Combita', 'department_id' => 7]);
        City::create(['name' => 'Coper', 'department_id' => 7]);
        City::create(['name' => 'Corrales', 'department_id' => 7]);
        City::create(['name' => 'Covarachia', 'department_id' => 7]);
        City::create(['name' => 'Cubara', 'department_id' => 7]);
        City::create(['name' => 'Cucaita', 'department_id' => 7]);
        City::create(['name' => 'Cuitiva', 'department_id' => 7]);
        City::create(['name' => 'Chiquiza', 'department_id' => 7]);
        City::create(['name' => 'Chivor', 'department_id' => 7]);
        City::create(['name' => 'Duitama', 'department_id' => 7]);
        City::create(['name' => 'El cocuy', 'department_id' => 7]);
        City::create(['name' => 'El espino', 'department_id' => 7]);
        City::create(['name' => 'Firavitoba', 'department_id' => 7]);
        City::create(['name' => 'Floresta', 'department_id' => 7]);
        City::create(['name' => 'Gachantiva', 'department_id' => 7]);
        City::create(['name' => 'Gameza', 'department_id' => 7]);
        City::create(['name' => 'Garagoa', 'department_id' => 7]);
        City::create(['name' => 'Guacamayas', 'department_id' => 7]);
        City::create(['name' => 'Guateque', 'department_id' => 7]);
        City::create(['name' => 'Guayata', 'department_id' => 7]);
        City::create(['name' => 'Gsican', 'department_id' => 7]);
        City::create(['name' => 'Iza', 'department_id' => 7]);
        City::create(['name' => 'Jenesano', 'department_id' => 7]);
        City::create(['name' => 'Jerico', 'department_id' => 7]);
        City::create(['name' => 'Labranzagrande', 'department_id' => 7]);
        City::create(['name' => 'La capilla', 'department_id' => 7]);
        City::create(['name' => 'La victoria', 'department_id' => 7]);
        City::create(['name' => 'La uvita', 'department_id' => 7]);
        City::create(['name' => 'Villa de leyva', 'department_id' => 7]);
        City::create(['name' => 'Macanal', 'department_id' => 7]);
        City::create(['name' => 'Maripi', 'department_id' => 7]);
        City::create(['name' => 'Miraflores', 'department_id' => 7]);
        City::create(['name' => 'Mongua', 'department_id' => 7]);
        City::create(['name' => 'Mongui', 'department_id' => 7]);
        City::create(['name' => 'Moniquira', 'department_id' => 7]);
        City::create(['name' => 'Motavita', 'department_id' => 7]);
        City::create(['name' => 'Muzo', 'department_id' => 7]);
        City::create(['name' => 'Nobsa', 'department_id' => 7]);
        City::create(['name' => 'Nuevo colon', 'department_id' => 7]);
        City::create(['name' => 'Oicata', 'department_id' => 7]);
        City::create(['name' => 'Otanche', 'department_id' => 7]);
        City::create(['name' => 'Pachavita', 'department_id' => 7]);
        City::create(['name' => 'Paez', 'department_id' => 7]);
        City::create(['name' => 'Paipa', 'department_id' => 7]);
        City::create(['name' => 'Pajarito', 'department_id' => 7]);
        City::create(['name' => 'Panqueba', 'department_id' => 7]);
        City::create(['name' => 'Pauna', 'department_id' => 7]);
        City::create(['name' => 'Paya', 'department_id' => 7]);
        City::create(['name' => 'Paz de rio', 'department_id' => 7]);
        City::create(['name' => 'Pesca', 'department_id' => 7]);
        City::create(['name' => 'Pisba', 'department_id' => 7]);
        City::create(['name' => 'Puerto boyaca', 'department_id' => 7]);
        City::create(['name' => 'Quipama', 'department_id' => 7]);
        City::create(['name' => 'Ramiriqui', 'department_id' => 7]);
        City::create(['name' => 'Raquira', 'department_id' => 7]);
        City::create(['name' => 'Rondon', 'department_id' => 7]);
        City::create(['name' => 'Saboya', 'department_id' => 7]);
        City::create(['name' => 'Sachica', 'department_id' => 7]);
        City::create(['name' => 'Samaca', 'department_id' => 7]);
        City::create(['name' => 'San eduardo', 'department_id' => 7]);
        City::create(['name' => 'San jose de pare', 'department_id' => 7]);
        City::create(['name' => 'San luis de gaceno', 'department_id' => 7]);
        City::create(['name' => 'San mateo', 'department_id' => 7]);
        City::create(['name' => 'San miguel de sema', 'department_id' => 7]);
        City::create(['name' => 'San pablo de borbur', 'department_id' => 7]);
        City::create(['name' => 'Santana', 'department_id' => 7]);
        City::create(['name' => 'Santa maria', 'department_id' => 7]);
        City::create(['name' => 'Santa rosa de viterbo', 'department_id' => 7]);
        City::create(['name' => 'Santa sofia', 'department_id' => 7]);
        City::create(['name' => 'Sativanorte', 'department_id' => 7]);
        City::create(['name' => 'Sativasur', 'department_id' => 7]);
        City::create(['name' => 'Siachoque', 'department_id' => 7]);
        City::create(['name' => 'Soata', 'department_id' => 7]);
        City::create(['name' => 'Socota', 'department_id' => 7]);
        City::create(['name' => 'Socha', 'department_id' => 7]);
        City::create(['name' => 'Sogamoso', 'department_id' => 7]);
        City::create(['name' => 'Somondoco', 'department_id' => 7]);
        City::create(['name' => 'Sora', 'department_id' => 7]);
        City::create(['name' => 'Sotaquira', 'department_id' => 7]);
        City::create(['name' => 'Soraca', 'department_id' => 7]);
        City::create(['name' => 'Susacon', 'department_id' => 7]);
        City::create(['name' => 'Sutamarchan', 'department_id' => 7]);
        City::create(['name' => 'Sutatenza', 'department_id' => 7]);
        City::create(['name' => 'Tasco', 'department_id' => 7]);
        City::create(['name' => 'Tenza', 'department_id' => 7]);
        City::create(['name' => 'Tibana', 'department_id' => 7]);
        City::create(['name' => 'Tibasosa', 'department_id' => 7]);
        City::create(['name' => 'Tinjaca', 'department_id' => 7]);
        City::create(['name' => 'Tipacoque', 'department_id' => 7]);
        City::create(['name' => 'Toca', 'department_id' => 7]);
        City::create(['name' => 'Togsi', 'department_id' => 7]);
        City::create(['name' => 'Topaga', 'department_id' => 7]);
        City::create(['name' => 'Tota', 'department_id' => 7]);
        City::create(['name' => 'Tunungua', 'department_id' => 7]);
        City::create(['name' => 'Turmeque', 'department_id' => 7]);
        City::create(['name' => 'Tuta', 'department_id' => 7]);
        City::create(['name' => 'Tutaza', 'department_id' => 7]);
        City::create(['name' => 'Umbita', 'department_id' => 7]);
        City::create(['name' => 'Ventaquemada', 'department_id' => 7]);
        City::create(['name' => 'Viracacha', 'department_id' => 7]);
        City::create(['name' => 'Zetaquira', 'department_id' => 7]);

        City::create(['name' => 'Manizales', 'department_id' => 8]);
        City::create(['name' => 'Aguadas', 'department_id' => 8]);
        City::create(['name' => 'Anserma', 'department_id' => 8]);
        City::create(['name' => 'Aranzazu', 'department_id' => 8]);
        City::create(['name' => 'Belalcazar', 'department_id' => 8]);
        City::create(['name' => 'Chinchina', 'department_id' => 8]);
        City::create(['name' => 'Filadelfia', 'department_id' => 8]);
        City::create(['name' => 'La dorada', 'department_id' => 8]);
        City::create(['name' => 'La merced', 'department_id' => 8]);
        City::create(['name' => 'Manzanares', 'department_id' => 8]);
        City::create(['name' => 'Marmato', 'department_id' => 8]);
        City::create(['name' => 'Marquetalia', 'department_id' => 8]);
        City::create(['name' => 'Marulanda', 'department_id' => 8]);
        City::create(['name' => 'Neira', 'department_id' => 8]);
        City::create(['name' => 'Norcasia', 'department_id' => 8]);
        City::create(['name' => 'Pacora', 'department_id' => 8]);
        City::create(['name' => 'Palestina', 'department_id' => 8]);
        City::create(['name' => 'Pensilvania', 'department_id' => 8]);
        City::create(['name' => 'Riosucio', 'department_id' => 8]);
        City::create(['name' => 'Risaralda', 'department_id' => 8]);
        City::create(['name' => 'Salamina', 'department_id' => 8]);
        City::create(['name' => 'Samana', 'department_id' => 8]);
        City::create(['name' => 'San jose', 'department_id' => 8]);
        City::create(['name' => 'Supia', 'department_id' => 8]);
        City::create(['name' => 'Victoria', 'department_id' => 8]);
        City::create(['name' => 'Villamaria', 'department_id' => 8]);
        City::create(['name' => 'Viterbo', 'department_id' => 8]);

        City::create(['name' => 'Florencia', 'department_id' => 9]);
        City::create(['name' => 'Albania', 'department_id' => 9]);
        City::create(['name' => 'Belen de los andaquies', 'department_id' => 9]);
        City::create(['name' => 'Cartagena del chaira', 'department_id' => 9]);
        City::create(['name' => 'Curillo', 'department_id' => 9]);
        City::create(['name' => 'El doncello', 'department_id' => 9]);
        City::create(['name' => 'El paujil', 'department_id' => 9]);
        City::create(['name' => 'La montañita', 'department_id' => 9]);
        City::create(['name' => 'Milan', 'department_id' => 9]);
        City::create(['name' => 'Morelia', 'department_id' => 9]);
        City::create(['name' => 'Puerto rico', 'department_id' => 9]);
        City::create(['name' => 'San jose del fragua', 'department_id' => 9]);
        City::create(['name' => 'San vicente del caguan', 'department_id' => 9]);
        City::create(['name' => 'Solano', 'department_id' => 9]);
        City::create(['name' => 'Solita', 'department_id' => 9]);
        City::create(['name' => 'Valparaiso', 'department_id' => 9]);

        City::create(['name' => 'Yopal', 'department_id' => 10]);
        City::create(['name' => 'Aguazul', 'department_id' => 10]);
        City::create(['name' => 'Chameza', 'department_id' => 10]);
        City::create(['name' => 'Hato corozal', 'department_id' => 10]);
        City::create(['name' => 'La salina', 'department_id' => 10]);
        City::create(['name' => 'Mani', 'department_id' => 10]);
        City::create(['name' => 'Monterrey', 'department_id' => 10]);
        City::create(['name' => 'Nunchia', 'department_id' => 10]);
        City::create(['name' => 'Orocue', 'department_id' => 10]);
        City::create(['name' => 'Paz de ariporo', 'department_id' => 10]);
        City::create(['name' => 'Pore', 'department_id' => 10]);
        City::create(['name' => 'Recetor', 'department_id' => 10]);
        City::create(['name' => 'Sabanalarga', 'department_id' => 10]);
        City::create(['name' => 'Sacama', 'department_id' => 10]);
        City::create(['name' => 'San luis de palenque', 'department_id' => 10]);
        City::create(['name' => 'Tamara', 'department_id' => 10]);
        City::create(['name' => 'Tauramena', 'department_id' => 10]);
        City::create(['name' => 'Trinidad', 'department_id' => 10]);
        City::create(['name' => 'Villanueva', 'department_id' => 10]);

        City::create(['name' => 'Popayan', 'department_id' => 11]);
        City::create(['name' => 'Almaguer', 'department_id' => 11]);
        City::create(['name' => 'Argelia', 'department_id' => 11]);
        City::create(['name' => 'Balboa', 'department_id' => 11]);
        City::create(['name' => 'Bolivar', 'department_id' => 11]);
        City::create(['name' => 'Buenos aires', 'department_id' => 11]);
        City::create(['name' => 'Cajibio', 'department_id' => 11]);
        City::create(['name' => 'Caldono', 'department_id' => 11]);
        City::create(['name' => 'Caloto', 'department_id' => 11]);
        City::create(['name' => 'Corinto', 'department_id' => 11]);
        City::create(['name' => 'El tambo', 'department_id' => 11]);
        City::create(['name' => 'Florencia', 'department_id' => 11]);
        City::create(['name' => 'Guachene', 'department_id' => 11]);
        City::create(['name' => 'Guapi', 'department_id' => 11]);
        City::create(['name' => 'Inza', 'department_id' => 11]);
        City::create(['name' => 'Jambalo', 'department_id' => 11]);
        City::create(['name' => 'La sierra', 'department_id' => 11]);
        City::create(['name' => 'La vega', 'department_id' => 11]);
        City::create(['name' => 'Lopez', 'department_id' => 11]);
        City::create(['name' => 'Mercaderes', 'department_id' => 11]);
        City::create(['name' => 'Miranda', 'department_id' => 11]);
        City::create(['name' => 'Morales', 'department_id' => 11]);
        City::create(['name' => 'Padilla', 'department_id' => 11]);
        City::create(['name' => 'Paez', 'department_id' => 11]);
        City::create(['name' => 'Patia', 'department_id' => 11]);
        City::create(['name' => 'Piamonte', 'department_id' => 11]);
        City::create(['name' => 'Piendamo', 'department_id' => 11]);
        City::create(['name' => 'Puerto tejada', 'department_id' => 11]);
        City::create(['name' => 'Purace', 'department_id' => 11]);
        City::create(['name' => 'Rosas', 'department_id' => 11]);
        City::create(['name' => 'San sebastian', 'department_id' => 11]);
        City::create(['name' => 'Santander de quilichao', 'department_id' => 11]);
        City::create(['name' => 'Santa rosa', 'department_id' => 11]);
        City::create(['name' => 'Silvia', 'department_id' => 11]);
        City::create(['name' => 'Sotara', 'department_id' => 11]);
        City::create(['name' => 'Suarez', 'department_id' => 11]);
        City::create(['name' => 'Sucre', 'department_id' => 11]);
        City::create(['name' => 'Timbio', 'department_id' => 11]);
        City::create(['name' => 'Timbiqui', 'department_id' => 11]);
        City::create(['name' => 'Toribio', 'department_id' => 11]);
        City::create(['name' => 'Totoro', 'department_id' => 11]);
        City::create(['name' => 'Villa rica', 'department_id' => 11]);

        City::create(['name' => 'Valledupar', 'department_id' => 12]);
        City::create(['name' => 'Aguachica', 'department_id' => 12]);
        City::create(['name' => 'Agustin codazzi', 'department_id' => 12]);
        City::create(['name' => 'Astrea', 'department_id' => 12]);
        City::create(['name' => 'Becerril', 'department_id' => 12]);
        City::create(['name' => 'Bosconia', 'department_id' => 12]);
        City::create(['name' => 'Chimichagua', 'department_id' => 12]);
        City::create(['name' => 'Chiriguana', 'department_id' => 12]);
        City::create(['name' => 'Curumani', 'department_id' => 12]);
        City::create(['name' => 'El copey', 'department_id' => 12]);
        City::create(['name' => 'El paso', 'department_id' => 12]);
        City::create(['name' => 'Gamarra', 'department_id' => 12]);
        City::create(['name' => 'Gonzalez', 'department_id' => 12]);
        City::create(['name' => 'La gloria', 'department_id' => 12]);
        City::create(['name' => 'La jagua de ibirico', 'department_id' => 12]);
        City::create(['name' => 'Manaure', 'department_id' => 12]);
        City::create(['name' => 'Pailitas', 'department_id' => 12]);
        City::create(['name' => 'Pelaya', 'department_id' => 12]);
        City::create(['name' => 'Pueblo bello', 'department_id' => 12]);
        City::create(['name' => 'Rio de oro', 'department_id' => 12]);
        City::create(['name' => 'La paz', 'department_id' => 12]);
        City::create(['name' => 'San alberto', 'department_id' => 12]);
        City::create(['name' => 'San diego', 'department_id' => 12]);
        City::create(['name' => 'San martin', 'department_id' => 12]);
        City::create(['name' => 'Tamalameque', 'department_id' => 12]);

        City::create(['name' => 'Quibdo', 'department_id' => 13]);
        City::create(['name' => 'Acandi', 'department_id' => 13]);
        City::create(['name' => 'Alto baudo', 'department_id' => 13]);
        City::create(['name' => 'Atrato', 'department_id' => 13]);
        City::create(['name' => 'Bagado', 'department_id' => 13]);
        City::create(['name' => 'Bahia solano', 'department_id' => 13]);
        City::create(['name' => 'Bajo baudo', 'department_id' => 13]);
        City::create(['name' => 'Bojaya', 'department_id' => 13]);
        City::create(['name' => 'El canton del san pablo', 'department_id' => 13]);
        City::create(['name' => 'Carmen del darien', 'department_id' => 13]);
        City::create(['name' => 'Certegui', 'department_id' => 13]);
        City::create(['name' => 'Condoto', 'department_id' => 13]);
        City::create(['name' => 'El carmen de atrato', 'department_id' => 13]);
        City::create(['name' => 'El litoral del san juan', 'department_id' => 13]);
        City::create(['name' => 'Istmina', 'department_id' => 13]);
        City::create(['name' => 'Jurado', 'department_id' => 13]);
        City::create(['name' => 'Lloro', 'department_id' => 13]);
        City::create(['name' => 'Medio atrato', 'department_id' => 13]);
        City::create(['name' => 'Medio baudo', 'department_id' => 13]);
        City::create(['name' => 'Medio san juan', 'department_id' => 13]);
        City::create(['name' => 'Novita', 'department_id' => 13]);
        City::create(['name' => 'Nuqui', 'department_id' => 13]);
        City::create(['name' => 'Rio iro', 'department_id' => 13]);
        City::create(['name' => 'Rio quito', 'department_id' => 13]);
        City::create(['name' => 'Riosucio', 'department_id' => 13]);
        City::create(['name' => 'San jose del palmar', 'department_id' => 13]);
        City::create(['name' => 'Sipi', 'department_id' => 13]);
        City::create(['name' => 'Tado', 'department_id' => 13]);
        City::create(['name' => 'Unguia', 'department_id' => 13]);
        City::create(['name' => 'Union panamericana', 'department_id' => 13]);

        City::create(['name' => 'Monteria', 'department_id' => 14]);
        City::create(['name' => 'Ayapel', 'department_id' => 14]);
        City::create(['name' => 'Buenavista', 'department_id' => 14]);
        City::create(['name' => 'Canalete', 'department_id' => 14]);
        City::create(['name' => 'Cerete', 'department_id' => 14]);
        City::create(['name' => 'Chima', 'department_id' => 14]);
        City::create(['name' => 'Chinu', 'department_id' => 14]);
        City::create(['name' => 'Cienaga de oro', 'department_id' => 14]);
        City::create(['name' => 'Cotorra', 'department_id' => 14]);
        City::create(['name' => 'La apartada', 'department_id' => 14]);
        City::create(['name' => 'Lorica', 'department_id' => 14]);
        City::create(['name' => 'Los cordobas', 'department_id' => 14]);
        City::create(['name' => 'Momil', 'department_id' => 14]);
        City::create(['name' => 'Montelibano', 'department_id' => 14]);
        City::create(['name' => 'Moñitos', 'department_id' => 14]);
        City::create(['name' => 'Planeta rica', 'department_id' => 14]);
        City::create(['name' => 'Pueblo nuevo', 'department_id' => 14]);
        City::create(['name' => 'Puerto escondido', 'department_id' => 14]);
        City::create(['name' => 'Puerto libertador', 'department_id' => 14]);
        City::create(['name' => 'Purisima', 'department_id' => 14]);
        City::create(['name' => 'Sahagun', 'department_id' => 14]);
        City::create(['name' => 'San andres sotavento', 'department_id' => 14]);
        City::create(['name' => 'San antero', 'department_id' => 14]);
        City::create(['name' => 'San bernardo del viento', 'department_id' => 14]);
        City::create(['name' => 'San carlos', 'department_id' => 14]);
        City::create(['name' => 'San pelayo', 'department_id' => 14]);
        City::create(['name' => 'Tierralta', 'department_id' => 14]);
        City::create(['name' => 'Valencia', 'department_id' => 14]);

        City::create(['name' => 'Cabrera', 'department_id' => 15]);
        City::create(['name' => 'Alban', 'department_id' => 15]);
        City::create(['name' => 'Anapoima', 'department_id' => 15]);
        City::create(['name' => 'Anolaima', 'department_id' => 15]);
        City::create(['name' => 'Arbelaez', 'department_id' => 15]);
        City::create(['name' => 'Beltran', 'department_id' => 15]);
        City::create(['name' => 'Bituima', 'department_id' => 15]);
        City::create(['name' => 'Bojaca', 'department_id' => 15]);
        City::create(['name' => 'Cabrera', 'department_id' => 15]);
        City::create(['name' => 'Cachipay', 'department_id' => 15]);
        City::create(['name' => 'Cajica', 'department_id' => 15]);
        City::create(['name' => 'Caparrapi', 'department_id' => 15]);
        City::create(['name' => 'Caqueza', 'department_id' => 15]);
        City::create(['name' => 'Carmen de carupa', 'department_id' => 15]);
        City::create(['name' => 'Chaguani', 'department_id' => 15]);
        City::create(['name' => 'Chia', 'department_id' => 15]);
        City::create(['name' => 'Chipaque', 'department_id' => 15]);
        City::create(['name' => 'Choachi', 'department_id' => 15]);
        City::create(['name' => 'Choconta', 'department_id' => 15]);
        City::create(['name' => 'Cogua', 'department_id' => 15]);
        City::create(['name' => 'Cota', 'department_id' => 15]);
        City::create(['name' => 'Cucunuba', 'department_id' => 15]);
        City::create(['name' => 'El colegio', 'department_id' => 15]);
        City::create(['name' => 'El peñon', 'department_id' => 15]);
        City::create(['name' => 'El rosal', 'department_id' => 15]);
        City::create(['name' => 'Facatativa', 'department_id' => 15]);
        City::create(['name' => 'Fomeque', 'department_id' => 15]);
        City::create(['name' => 'Fosca', 'department_id' => 15]);
        City::create(['name' => 'Funza', 'department_id' => 15]);
        City::create(['name' => 'Fuquene', 'department_id' => 15]);
        City::create(['name' => 'Fusagasuga', 'department_id' => 15]);
        City::create(['name' => 'Gachala', 'department_id' => 15]);
        City::create(['name' => 'Gachancipa', 'department_id' => 15]);
        City::create(['name' => 'Gacheta', 'department_id' => 15]);
        City::create(['name' => 'Gama', 'department_id' => 15]);
        City::create(['name' => 'Girardot', 'department_id' => 15]);
        City::create(['name' => 'Granada', 'department_id' => 15]);
        City::create(['name' => 'Guacheta', 'department_id' => 15]);
        City::create(['name' => 'Guaduas', 'department_id' => 15]);
        City::create(['name' => 'Guasca', 'department_id' => 15]);
        City::create(['name' => 'Guataqui', 'department_id' => 15]);
        City::create(['name' => 'Guatavita', 'department_id' => 15]);
        City::create(['name' => 'Guayabal de siquima', 'department_id' => 15]);
        City::create(['name' => 'Guayabetal', 'department_id' => 15]);
        City::create(['name' => 'Gutierrez', 'department_id' => 15]);
        City::create(['name' => 'Jerusalen', 'department_id' => 15]);
        City::create(['name' => 'Junin', 'department_id' => 15]);
        City::create(['name' => 'La calera', 'department_id' => 15]);
        City::create(['name' => 'La mesa', 'department_id' => 15]);
        City::create(['name' => 'La palma', 'department_id' => 15]);
        City::create(['name' => 'La peña', 'department_id' => 15]);
        City::create(['name' => 'La vega', 'department_id' => 15]);
        City::create(['name' => 'Lenguazaque', 'department_id' => 15]);
        City::create(['name' => 'Macheta', 'department_id' => 15]);
        City::create(['name' => 'Madrid', 'department_id' => 15]);
        City::create(['name' => 'Manta', 'department_id' => 15]);
        City::create(['name' => 'Medina', 'department_id' => 15]);
        City::create(['name' => 'Mosquera', 'department_id' => 15]);
        City::create(['name' => 'Nariño', 'department_id' => 15]);
        City::create(['name' => 'Nemocon', 'department_id' => 15]);
        City::create(['name' => 'Nilo', 'department_id' => 15]);
        City::create(['name' => 'Nimaima', 'department_id' => 15]);
        City::create(['name' => 'Nocaima', 'department_id' => 15]);
        City::create(['name' => 'Venecia', 'department_id' => 15]);
        City::create(['name' => 'Pacho', 'department_id' => 15]);
        City::create(['name' => 'Paime', 'department_id' => 15]);
        City::create(['name' => 'Pandi', 'department_id' => 15]);
        City::create(['name' => 'Paratebueno', 'department_id' => 15]);
        City::create(['name' => 'Pasca', 'department_id' => 15]);
        City::create(['name' => 'Puerto salgar', 'department_id' => 15]);
        City::create(['name' => 'Puli', 'department_id' => 15]);
        City::create(['name' => 'Quebradanegra', 'department_id' => 15]);
        City::create(['name' => 'Quetame', 'department_id' => 15]);
        City::create(['name' => 'Quipile', 'department_id' => 15]);
        City::create(['name' => 'Apulo', 'department_id' => 15]);
        City::create(['name' => 'Ricaurte', 'department_id' => 15]);
        City::create(['name' => 'San antonio del tequendama', 'department_id' => 15]);
        City::create(['name' => 'San bernardo', 'department_id' => 15]);
        City::create(['name' => 'San cayetano', 'department_id' => 15]);
        City::create(['name' => 'San francisco', 'department_id' => 15]);
        City::create(['name' => 'San juan de rio seco', 'department_id' => 15]);
        City::create(['name' => 'Sasaima', 'department_id' => 15]);
        City::create(['name' => 'Sesquile', 'department_id' => 15]);
        City::create(['name' => 'Sibate', 'department_id' => 15]);
        City::create(['name' => 'Silvania', 'department_id' => 15]);
        City::create(['name' => 'Simijaca', 'department_id' => 15]);
        City::create(['name' => 'Soacha', 'department_id' => 15]);
        City::create(['name' => 'Sopo', 'department_id' => 15]);
        City::create(['name' => 'Subachoque', 'department_id' => 15]);
        City::create(['name' => 'Suesca', 'department_id' => 15]);
        City::create(['name' => 'Supata', 'department_id' => 15]);
        City::create(['name' => 'Susa', 'department_id' => 15]);
        City::create(['name' => 'Sutatausa', 'department_id' => 15]);
        City::create(['name' => 'Tabio', 'department_id' => 15]);
        City::create(['name' => 'Tausa', 'department_id' => 15]);
        City::create(['name' => 'Tena', 'department_id' => 15]);
        City::create(['name' => 'Tenjo', 'department_id' => 15]);
        City::create(['name' => 'Tibacuy', 'department_id' => 15]);
        City::create(['name' => 'Tibirita', 'department_id' => 15]);
        City::create(['name' => 'Tocaima', 'department_id' => 15]);
        City::create(['name' => 'Tocancipa', 'department_id' => 15]);
        City::create(['name' => 'Topaipi', 'department_id' => 15]);
        City::create(['name' => 'Ubala', 'department_id' => 15]);
        City::create(['name' => 'Ubaque', 'department_id' => 15]);
        City::create(['name' => 'Villa de san diego de ubate', 'department_id' => 15]);
        City::create(['name' => 'Une', 'department_id' => 15]);
        City::create(['name' => 'Utica', 'department_id' => 15]);
        City::create(['name' => 'Vergara', 'department_id' => 15]);
        City::create(['name' => 'Viani', 'department_id' => 15]);
        City::create(['name' => 'Villagomez', 'department_id' => 15]);
        City::create(['name' => 'Villapinzon', 'department_id' => 15]);
        City::create(['name' => 'Villeta', 'department_id' => 15]);
        City::create(['name' => 'Viota', 'department_id' => 15]);
        City::create(['name' => 'Yacopi', 'department_id' => 15]);
        City::create(['name' => 'Zipacon', 'department_id' => 15]);
        City::create(['name' => 'Zipaquira', 'department_id' => 15]);

        City::create(['name' => 'Inirida', 'department_id' => 16]);
        City::create(['name' => 'Barranco minas', 'department_id' => 16]);
        City::create(['name' => 'Mapiripana', 'department_id' => 16]);
        City::create(['name' => 'San felipe', 'department_id' => 16]);
        City::create(['name' => 'Puerto colombia', 'department_id' => 16]);
        City::create(['name' => 'La guadalupe', 'department_id' => 16]);
        City::create(['name' => 'Cacahual', 'department_id' => 16]);
        City::create(['name' => 'Pana pana', 'department_id' => 16]);
        City::create(['name' => 'Morichal', 'department_id' => 16]);

        City::create(['name' => 'San jose del guaviare', 'department_id' => 17]);
        City::create(['name' => 'Calamar', 'department_id' => 17]);
        City::create(['name' => 'El retorno', 'department_id' => 17]);
        City::create(['name' => 'Miraflores', 'department_id' => 17]);

        City::create(['name' => 'Neiva', 'department_id' => 18]);
        City::create(['name' => 'Acevedo', 'department_id' => 18]);
        City::create(['name' => 'Agrado', 'department_id' => 18]);
        City::create(['name' => 'Aipe', 'department_id' => 18]);
        City::create(['name' => 'Algeciras', 'department_id' => 18]);
        City::create(['name' => 'Altamira', 'department_id' => 18]);
        City::create(['name' => 'Baraya', 'department_id' => 18]);
        City::create(['name' => 'Campoalegre', 'department_id' => 18]);
        City::create(['name' => 'Colombia', 'department_id' => 18]);
        City::create(['name' => 'Elias', 'department_id' => 18]);
        City::create(['name' => 'Garzon', 'department_id' => 18]);
        City::create(['name' => 'Gigante', 'department_id' => 18]);
        City::create(['name' => 'Guadalupe', 'department_id' => 18]);
        City::create(['name' => 'Hobo', 'department_id' => 18]);
        City::create(['name' => 'Iquira', 'department_id' => 18]);
        City::create(['name' => 'Isnos', 'department_id' => 18]);
        City::create(['name' => 'La argentina', 'department_id' => 18]);
        City::create(['name' => 'La plata', 'department_id' => 18]);
        City::create(['name' => 'Nataga', 'department_id' => 18]);
        City::create(['name' => 'Oporapa', 'department_id' => 18]);
        City::create(['name' => 'Paicol', 'department_id' => 18]);
        City::create(['name' => 'Palermo', 'department_id' => 18]);
        City::create(['name' => 'Palestina', 'department_id' => 18]);
        City::create(['name' => 'Pital', 'department_id' => 18]);
        City::create(['name' => 'Pitalito', 'department_id' => 18]);
        City::create(['name' => 'Rivera', 'department_id' => 18]);
        City::create(['name' => 'Saladoblanco', 'department_id' => 18]);
        City::create(['name' => 'San agustin', 'department_id' => 18]);
        City::create(['name' => 'Santa maria', 'department_id' => 18]);
        City::create(['name' => 'Suaza', 'department_id' => 18]);
        City::create(['name' => 'Tarqui', 'department_id' => 18]);
        City::create(['name' => 'Tesalia', 'department_id' => 18]);
        City::create(['name' => 'Tello', 'department_id' => 18]);
        City::create(['name' => 'Teruel', 'department_id' => 18]);
        City::create(['name' => 'Timana', 'department_id' => 18]);
        City::create(['name' => 'Villavieja', 'department_id' => 18]);
        City::create(['name' => 'Yaguara', 'department_id' => 18]);

        City::create(['name' => 'Riohacha', 'department_id' => 19]);
        City::create(['name' => 'Albania', 'department_id' => 19]);
        City::create(['name' => 'Barrancas', 'department_id' => 19]);
        City::create(['name' => 'Dibulla', 'department_id' => 19]);
        City::create(['name' => 'Distraccion', 'department_id' => 19]);
        City::create(['name' => 'El molino', 'department_id' => 19]);
        City::create(['name' => 'Fonseca', 'department_id' => 19]);
        City::create(['name' => 'Hatonuevo', 'department_id' => 19]);
        City::create(['name' => 'La jagua del pilar', 'department_id' => 19]);
        City::create(['name' => 'Maicao', 'department_id' => 19]);
        City::create(['name' => 'Manaure', 'department_id' => 19]);
        City::create(['name' => 'San juan del cesar', 'department_id' => 19]);
        City::create(['name' => 'Uribia', 'department_id' => 19]);
        City::create(['name' => 'Urumita', 'department_id' => 19]);
        City::create(['name' => 'Villanueva', 'department_id' => 19]);

        City::create(['name' => 'Santa marta', 'department_id' => 20]);
        City::create(['name' => 'Algarrobo', 'department_id' => 20]);
        City::create(['name' => 'Aracataca', 'department_id' => 20]);
        City::create(['name' => 'Ariguani', 'department_id' => 20]);
        City::create(['name' => 'Cerro san antonio', 'department_id' => 20]);
        City::create(['name' => 'Chibolo', 'department_id' => 20]);
        City::create(['name' => 'Cienaga', 'department_id' => 20]);
        City::create(['name' => 'Concordia', 'department_id' => 20]);
        City::create(['name' => 'El banco', 'department_id' => 20]);
        City::create(['name' => 'El piñon', 'department_id' => 20]);
        City::create(['name' => 'El reten', 'department_id' => 20]);
        City::create(['name' => 'Fundacion', 'department_id' => 20]);
        City::create(['name' => 'Guamal', 'department_id' => 20]);
        City::create(['name' => 'Nueva granada', 'department_id' => 20]);
        City::create(['name' => 'Pedraza', 'department_id' => 20]);
        City::create(['name' => 'Pijiño del carmen', 'department_id' => 20]);
        City::create(['name' => 'Pivijay', 'department_id' => 20]);
        City::create(['name' => 'Plato', 'department_id' => 20]);
        City::create(['name' => 'Puebloviejo', 'department_id' => 20]);
        City::create(['name' => 'Remolino', 'department_id' => 20]);
        City::create(['name' => 'Sabanas de san angel', 'department_id' => 20]);
        City::create(['name' => 'Salamina', 'department_id' => 20]);
        City::create(['name' => 'San sebastian de buenavista', 'department_id' => 20]);
        City::create(['name' => 'San zenon', 'department_id' => 20]);
        City::create(['name' => 'Santa ana', 'department_id' => 20]);
        City::create(['name' => 'Santa barbara de pinto', 'department_id' => 20]);
        City::create(['name' => 'Sitionuevo', 'department_id' => 20]);
        City::create(['name' => 'Tenerife', 'department_id' => 20]);
        City::create(['name' => 'Zapayan', 'department_id' => 20]);
        City::create(['name' => 'Zona bananera', 'department_id' => 20]);

        City::create(['name' => 'Villavicencio', 'department_id' => 21]);
        City::create(['name' => 'Acacias', 'department_id' => 21]);
        City::create(['name' => 'Barranca de upia', 'department_id' => 21]);
        City::create(['name' => 'Cabuyaro', 'department_id' => 21]);
        City::create(['name' => 'Castilla la nueva', 'department_id' => 21]);
        City::create(['name' => 'Cubarral', 'department_id' => 21]);
        City::create(['name' => 'Cumaral', 'department_id' => 21]);
        City::create(['name' => 'El calvario', 'department_id' => 21]);
        City::create(['name' => 'El castillo', 'department_id' => 21]);
        City::create(['name' => 'El dorado', 'department_id' => 21]);
        City::create(['name' => 'Fuente de oro', 'department_id' => 21]);
        City::create(['name' => 'Granada', 'department_id' => 21]);
        City::create(['name' => 'Guamal', 'department_id' => 21]);
        City::create(['name' => 'Mapiripan', 'department_id' => 21]);
        City::create(['name' => 'Mesetas', 'department_id' => 21]);
        City::create(['name' => 'La macarena', 'department_id' => 21]);
        City::create(['name' => 'Uribe', 'department_id' => 21]);
        City::create(['name' => 'Lejanias', 'department_id' => 21]);
        City::create(['name' => 'Puerto concordia', 'department_id' => 21]);
        City::create(['name' => 'Puerto gaitan', 'department_id' => 21]);
        City::create(['name' => 'Puerto lopez', 'department_id' => 21]);
        City::create(['name' => 'Puerto lleras', 'department_id' => 21]);
        City::create(['name' => 'Puerto rico', 'department_id' => 21]);
        City::create(['name' => 'Restrepo', 'department_id' => 21]);
        City::create(['name' => 'San carlos de guaroa', 'department_id' => 21]);
        City::create(['name' => 'San juan de arama', 'department_id' => 21]);
        City::create(['name' => 'San juanito', 'department_id' => 21]);
        City::create(['name' => 'San martin', 'department_id' => 21]);
        City::create(['name' => 'Vistahermosa', 'department_id' => 21]);

        City::create(['name' => 'Pasto', 'department_id' => 22]);
        City::create(['name' => 'Alban', 'department_id' => 22]);
        City::create(['name' => 'Aldana', 'department_id' => 22]);
        City::create(['name' => 'Ancuya', 'department_id' => 22]);
        City::create(['name' => 'Arboleda', 'department_id' => 22]);
        City::create(['name' => 'Barbacoas', 'department_id' => 22]);
        City::create(['name' => 'Belen', 'department_id' => 22]);
        City::create(['name' => 'Buesaco', 'department_id' => 22]);
        City::create(['name' => 'Colon', 'department_id' => 22]);
        City::create(['name' => 'Consaca', 'department_id' => 22]);
        City::create(['name' => 'Contadero', 'department_id' => 22]);
        City::create(['name' => 'Cordoba', 'department_id' => 22]);
        City::create(['name' => 'Cuaspud', 'department_id' => 22]);
        City::create(['name' => 'Cumbal', 'department_id' => 22]);
        City::create(['name' => 'Cumbitara', 'department_id' => 22]);
        City::create(['name' => 'Chachagsi', 'department_id' => 22]);
        City::create(['name' => 'El charco', 'department_id' => 22]);
        City::create(['name' => 'El peñol', 'department_id' => 22]);
        City::create(['name' => 'El rosario', 'department_id' => 22]);
        City::create(['name' => 'El tablon de gomez', 'department_id' => 22]);
        City::create(['name' => 'El tambo', 'department_id' => 22]);
        City::create(['name' => 'Funes', 'department_id' => 22]);
        City::create(['name' => 'Guachucal', 'department_id' => 22]);
        City::create(['name' => 'Guaitarilla', 'department_id' => 22]);
        City::create(['name' => 'Gualmatan', 'department_id' => 22]);
        City::create(['name' => 'Iles', 'department_id' => 22]);
        City::create(['name' => 'Imues', 'department_id' => 22]);
        City::create(['name' => 'Ipiales', 'department_id' => 22]);
        City::create(['name' => 'La cruz', 'department_id' => 22]);
        City::create(['name' => 'La florida', 'department_id' => 22]);
        City::create(['name' => 'La llanada', 'department_id' => 22]);
        City::create(['name' => 'La tola', 'department_id' => 22]);
        City::create(['name' => 'La union', 'department_id' => 22]);
        City::create(['name' => 'Leiva', 'department_id' => 22]);
        City::create(['name' => 'Linares', 'department_id' => 22]);
        City::create(['name' => 'Los andes', 'department_id' => 22]);
        City::create(['name' => 'Magsi', 'department_id' => 22]);
        City::create(['name' => 'Mallama', 'department_id' => 22]);
        City::create(['name' => 'Mosquera', 'department_id' => 22]);
        City::create(['name' => 'Nariño', 'department_id' => 22]);
        City::create(['name' => 'Olaya herrera', 'department_id' => 22]);
        City::create(['name' => 'Ospina', 'department_id' => 22]);
        City::create(['name' => 'Francisco pizarro', 'department_id' => 22]);
        City::create(['name' => 'Policarpa', 'department_id' => 22]);
        City::create(['name' => 'Potosi', 'department_id' => 22]);
        City::create(['name' => 'Providencia', 'department_id' => 22]);
        City::create(['name' => 'Puerres', 'department_id' => 22]);
        City::create(['name' => 'Pupiales', 'department_id' => 22]);
        City::create(['name' => 'Ricaurte', 'department_id' => 22]);
        City::create(['name' => 'Roberto payan', 'department_id' => 22]);
        City::create(['name' => 'Samaniego', 'department_id' => 22]);
        City::create(['name' => 'Sandona', 'department_id' => 22]);
        City::create(['name' => 'San Bernardo', 'department_id' => 22]);
        City::create(['name' => 'San Lorenzo', 'department_id' => 22]);
        City::create(['name' => 'San Pablo', 'department_id' => 22]);
        City::create(['name' => 'San Pedro de cartago', 'department_id' => 22]);
        City::create(['name' => 'Santa barbara', 'department_id' => 22]);
        City::create(['name' => 'Santacruz', 'department_id' => 22]);
        City::create(['name' => 'Sapuyes', 'department_id' => 22]);
        City::create(['name' => 'Taminango', 'department_id' => 22]);
        City::create(['name' => 'Tangua', 'department_id' => 22]);
        City::create(['name' => 'San Andres de tumaco', 'department_id' => 22]);
        City::create(['name' => 'Tuquerres', 'department_id' => 22]);
        City::create(['name' => 'Yacuanquer', 'department_id' => 22]);

        City::create(['name' => 'Cucuta', 'department_id' => 23]);
        City::create(['name' => 'Abrego', 'department_id' => 23]);
        City::create(['name' => 'Arboledas', 'department_id' => 23]);
        City::create(['name' => 'Bochalema', 'department_id' => 23]);
        City::create(['name' => 'Bucarasica', 'department_id' => 23]);
        City::create(['name' => 'Cacota', 'department_id' => 23]);
        City::create(['name' => 'Cachira', 'department_id' => 23]);
        City::create(['name' => 'Chinacota', 'department_id' => 23]);
        City::create(['name' => 'Chitaga', 'department_id' => 23]);
        City::create(['name' => 'Convencion', 'department_id' => 23]);
        City::create(['name' => 'Cucutilla', 'department_id' => 23]);
        City::create(['name' => 'Durania', 'department_id' => 23]);
        City::create(['name' => 'El carmen', 'department_id' => 23]);
        City::create(['name' => 'El tarra', 'department_id' => 23]);
        City::create(['name' => 'El zulia', 'department_id' => 23]);
        City::create(['name' => 'Gramalote', 'department_id' => 23]);
        City::create(['name' => 'Hacari', 'department_id' => 23]);
        City::create(['name' => 'Herran', 'department_id' => 23]);
        City::create(['name' => 'Labateca', 'department_id' => 23]);
        City::create(['name' => 'La esperanza', 'department_id' => 23]);
        City::create(['name' => 'La playa', 'department_id' => 23]);
        City::create(['name' => 'Los patios', 'department_id' => 23]);
        City::create(['name' => 'Lourdes', 'department_id' => 23]);
        City::create(['name' => 'Mutiscua', 'department_id' => 23]);
        City::create(['name' => 'Ocaña', 'department_id' => 23]);
        City::create(['name' => 'Pamplona', 'department_id' => 23]);
        City::create(['name' => 'Pamplonita', 'department_id' => 23]);
        City::create(['name' => 'Puerto santander', 'department_id' => 23]);
        City::create(['name' => 'Ragonvalia', 'department_id' => 23]);
        City::create(['name' => 'Salazar', 'department_id' => 23]);
        City::create(['name' => 'San calixto', 'department_id' => 23]);
        City::create(['name' => 'San cayetano', 'department_id' => 23]);
        City::create(['name' => 'Santiago', 'department_id' => 23]);
        City::create(['name' => 'Sardinata', 'department_id' => 23]);
        City::create(['name' => 'Silos', 'department_id' => 23]);
        City::create(['name' => 'Teorama', 'department_id' => 23]);
        City::create(['name' => 'Tibu', 'department_id' => 23]);
        City::create(['name' => 'Toledo', 'department_id' => 23]);
        City::create(['name' => 'Villa caro', 'department_id' => 23]);
        City::create(['name' => 'Villa del rosario', 'department_id' => 23]);

        City::create(['name' => 'Mocoa', 'department_id' => 24]);
        City::create(['name' => 'Colon', 'department_id' => 24]);
        City::create(['name' => 'Orito', 'department_id' => 24]);
        City::create(['name' => 'Puerto asis', 'department_id' => 24]);
        City::create(['name' => 'Puerto caicedo', 'department_id' => 24]);
        City::create(['name' => 'Puerto guzman', 'department_id' => 24]);
        City::create(['name' => 'Leguizamo', 'department_id' => 24]);
        City::create(['name' => 'Sibundoy', 'department_id' => 24]);
        City::create(['name' => 'San francisco', 'department_id' => 24]);
        City::create(['name' => 'San miguel', 'department_id' => 24]);
        City::create(['name' => 'Santiago', 'department_id' => 24]);
        City::create(['name' => 'Valle del guamuez', 'department_id' => 24]);
        City::create(['name' => 'Villagarzon', 'department_id' => 24]);

        City::create(['name' => 'Armenia', 'department_id' => 25]);
        City::create(['name' => 'Buenavista', 'department_id' => 25]);
        City::create(['name' => 'Calarca', 'department_id' => 25]);
        City::create(['name' => 'Circasia', 'department_id' => 25]);
        City::create(['name' => 'Cordoba', 'department_id' => 25]);
        City::create(['name' => 'Filandia', 'department_id' => 25]);
        City::create(['name' => 'Genova', 'department_id' => 25]);
        City::create(['name' => 'La tebaida', 'department_id' => 25]);
        City::create(['name' => 'Montenegro', 'department_id' => 25]);
        City::create(['name' => 'Pijao', 'department_id' => 25]);
        City::create(['name' => 'Quimbaya', 'department_id' => 25]);
        City::create(['name' => 'Salento', 'department_id' => 25]);

        City::create(['name' => 'Pereira', 'department_id' => 26]);
        City::create(['name' => 'Apia', 'department_id' => 26]);
        City::create(['name' => 'Balboa', 'department_id' => 26]);
        City::create(['name' => 'Belen de umbria', 'department_id' => 26]);
        City::create(['name' => 'Dosquebradas', 'department_id' => 26]);
        City::create(['name' => 'Guatica', 'department_id' => 26]);
        City::create(['name' => 'La celia', 'department_id' => 26]);
        City::create(['name' => 'La virginia', 'department_id' => 26]);
        City::create(['name' => 'Marsella', 'department_id' => 26]);
        City::create(['name' => 'Mistrato', 'department_id' => 26]);
        City::create(['name' => 'Pueblo rico', 'department_id' => 26]);
        City::create(['name' => 'Quinchia', 'department_id' => 26]);
        City::create(['name' => 'Santa rosa de cabal', 'department_id' => 26]);
        City::create(['name' => 'Santuario', 'department_id' => 26]);

        City::create(['name' => 'San andres', 'department_id' => 27]);
        City::create(['name' => 'Providencia', 'department_id' => 27]);

        City::create(['name' => 'Bucaramanga', 'department_id' => 28]);
        City::create(['name' => 'Aguada', 'department_id' => 28]);
        City::create(['name' => 'Albania', 'department_id' => 28]);
        City::create(['name' => 'Aratoca', 'department_id' => 28]);
        City::create(['name' => 'Barbosa', 'department_id' => 28]);
        City::create(['name' => 'Barichara', 'department_id' => 28]);
        City::create(['name' => 'Barrancabermeja', 'department_id' => 28]);
        City::create(['name' => 'Betulia', 'department_id' => 28]);
        City::create(['name' => 'Bolivar', 'department_id' => 28]);
        City::create(['name' => 'Cabrera', 'department_id' => 28]);
        City::create(['name' => 'California', 'department_id' => 28]);
        City::create(['name' => 'Capitanejo', 'department_id' => 28]);
        City::create(['name' => 'Carcasi', 'department_id' => 28]);
        City::create(['name' => 'Cepita', 'department_id' => 28]);
        City::create(['name' => 'Cerrito', 'department_id' => 28]);
        City::create(['name' => 'Charala', 'department_id' => 28]);
        City::create(['name' => 'Charta', 'department_id' => 28]);
        City::create(['name' => 'Chima', 'department_id' => 28]);
        City::create(['name' => 'Chipata', 'department_id' => 28]);
        City::create(['name' => 'Cimitarra', 'department_id' => 28]);
        City::create(['name' => 'Concepcion', 'department_id' => 28]);
        City::create(['name' => 'Confines', 'department_id' => 28]);
        City::create(['name' => 'Contratacion', 'department_id' => 28]);
        City::create(['name' => 'Coromoro', 'department_id' => 28]);
        City::create(['name' => 'Curiti', 'department_id' => 28]);
        City::create(['name' => 'El carmen de chucuri', 'department_id' => 28]);
        City::create(['name' => 'El guacamayo', 'department_id' => 28]);
        City::create(['name' => 'El peñon', 'department_id' => 28]);
        City::create(['name' => 'El playon', 'department_id' => 28]);
        City::create(['name' => 'Encino', 'department_id' => 28]);
        City::create(['name' => 'Enciso', 'department_id' => 28]);
        City::create(['name' => 'Florian', 'department_id' => 28]);
        City::create(['name' => 'Floridablanca', 'department_id' => 28]);
        City::create(['name' => 'Galan', 'department_id' => 28]);
        City::create(['name' => 'Gambita', 'department_id' => 28]);
        City::create(['name' => 'Giron', 'department_id' => 28]);
        City::create(['name' => 'Guaca', 'department_id' => 28]);
        City::create(['name' => 'Guadalupe', 'department_id' => 28]);
        City::create(['name' => 'Guapota', 'department_id' => 28]);
        City::create(['name' => 'Guavata', 'department_id' => 28]);
        City::create(['name' => 'Gsepsa', 'department_id' => 28]);
        City::create(['name' => 'Hato', 'department_id' => 28]);
        City::create(['name' => 'Jesus maria', 'department_id' => 28]);
        City::create(['name' => 'Jordan', 'department_id' => 28]);
        City::create(['name' => 'La belleza', 'department_id' => 28]);
        City::create(['name' => 'Landazuri', 'department_id' => 28]);
        City::create(['name' => 'La paz', 'department_id' => 28]);
        City::create(['name' => 'Lebrija', 'department_id' => 28]);
        City::create(['name' => 'Los santos', 'department_id' => 28]);
        City::create(['name' => 'Macaravita', 'department_id' => 28]);
        City::create(['name' => 'Malaga', 'department_id' => 28]);
        City::create(['name' => 'Matanza', 'department_id' => 28]);
        City::create(['name' => 'Mogotes', 'department_id' => 28]);
        City::create(['name' => 'Molagavita', 'department_id' => 28]);
        City::create(['name' => 'Ocamonte', 'department_id' => 28]);
        City::create(['name' => 'Oiba', 'department_id' => 28]);
        City::create(['name' => 'Onzaga', 'department_id' => 28]);
        City::create(['name' => 'Palmar', 'department_id' => 28]);
        City::create(['name' => 'Palmas del socorro', 'department_id' => 28]);
        City::create(['name' => 'Paramo', 'department_id' => 28]);
        City::create(['name' => 'Piedecuesta', 'department_id' => 28]);
        City::create(['name' => 'Pinchote', 'department_id' => 28]);
        City::create(['name' => 'Puente nacional', 'department_id' => 28]);
        City::create(['name' => 'Puerto parra', 'department_id' => 28]);
        City::create(['name' => 'Puerto wilches', 'department_id' => 28]);
        City::create(['name' => 'Rionegro', 'department_id' => 28]);
        City::create(['name' => 'Sabana de torres', 'department_id' => 28]);
        City::create(['name' => 'San andres', 'department_id' => 28]);
        City::create(['name' => 'San benito', 'department_id' => 28]);
        City::create(['name' => 'San gil', 'department_id' => 28]);
        City::create(['name' => 'San joaquin', 'department_id' => 28]);
        City::create(['name' => 'San jose de miranda', 'department_id' => 28]);
        City::create(['name' => 'San miguel', 'department_id' => 28]);
        City::create(['name' => 'San vicente de chucuri', 'department_id' => 28]);
        City::create(['name' => 'Santa barbara', 'department_id' => 28]);
        City::create(['name' => 'Santa helena del opon', 'department_id' => 28]);
        City::create(['name' => 'Simacota', 'department_id' => 28]);
        City::create(['name' => 'Socorro', 'department_id' => 28]);
        City::create(['name' => 'Suaita', 'department_id' => 28]);
        City::create(['name' => 'Sucre', 'department_id' => 28]);
        City::create(['name' => 'Surata', 'department_id' => 28]);
        City::create(['name' => 'Tona', 'department_id' => 28]);
        City::create(['name' => 'Valle de san jose', 'department_id' => 28]);
        City::create(['name' => 'Velez', 'department_id' => 28]);
        City::create(['name' => 'Vetas', 'department_id' => 28]);
        City::create(['name' => 'Villanueva', 'department_id' => 28]);
        City::create(['name' => 'Zapatoca', 'department_id' => 28]);

        City::create(['name' => 'Sincelejo', 'department_id' => 29]);
        City::create(['name' => 'Buenavista', 'department_id' => 29]);
        City::create(['name' => 'Caimito', 'department_id' => 29]);
        City::create(['name' => 'Coloso', 'department_id' => 29]);
        City::create(['name' => 'Corozal', 'department_id' => 29]);
        City::create(['name' => 'Coveñas', 'department_id' => 29]);
        City::create(['name' => 'Chalan', 'department_id' => 29]);
        City::create(['name' => 'El roble', 'department_id' => 29]);
        City::create(['name' => 'Galeras', 'department_id' => 29]);
        City::create(['name' => 'Guaranda', 'department_id' => 29]);
        City::create(['name' => 'La union', 'department_id' => 29]);
        City::create(['name' => 'Los palmitos', 'department_id' => 29]);
        City::create(['name' => 'Majagual', 'department_id' => 29]);
        City::create(['name' => 'Morroa', 'department_id' => 29]);
        City::create(['name' => 'Ovejas', 'department_id' => 29]);
        City::create(['name' => 'Palmito', 'department_id' => 29]);
        City::create(['name' => 'Sampues', 'department_id' => 29]);
        City::create(['name' => 'San benito abad', 'department_id' => 29]);
        City::create(['name' => 'San juan de betulia', 'department_id' => 29]);
        City::create(['name' => 'San marcos', 'department_id' => 29]);
        City::create(['name' => 'San onofre', 'department_id' => 29]);
        City::create(['name' => 'San pedro', 'department_id' => 29]);
        City::create(['name' => 'San luis de since', 'department_id' => 29]);
        City::create(['name' => 'Sucre', 'department_id' => 29]);
        City::create(['name' => 'Santiago de tolu', 'department_id' => 29]);
        City::create(['name' => 'Tolu viejo', 'department_id' => 29]);

        City::create(['name' => 'Ibagué', 'department_id' => 30]);
        City::create(['name' => 'Alpujarra', 'department_id' => 30]);
        City::create(['name' => 'Alvarado', 'department_id' => 30]);
        City::create(['name' => 'Ambalema', 'department_id' => 30]);
        City::create(['name' => 'Anzoategui', 'department_id' => 30]);
        City::create(['name' => 'Armero', 'department_id' => 30]);
        City::create(['name' => 'Ataco', 'department_id' => 30]);
        City::create(['name' => 'Cajamarca', 'department_id' => 30]);
        City::create(['name' => 'Carmen de apicalá', 'department_id' => 30]);
        City::create(['name' => 'Casabianca', 'department_id' => 30]);
        City::create(['name' => 'Chaparral', 'department_id' => 30]);
        City::create(['name' => 'Coello', 'department_id' => 30]);
        City::create(['name' => 'Coyaima', 'department_id' => 30]);
        City::create(['name' => 'Cunday', 'department_id' => 30]);
        City::create(['name' => 'Dolores', 'department_id' => 30]);
        City::create(['name' => 'Espinal', 'department_id' => 30]);
        City::create(['name' => 'Falan', 'department_id' => 30]);
        City::create(['name' => 'Flandes', 'department_id' => 30]);
        City::create(['name' => 'Fresno', 'department_id' => 30]);
        City::create(['name' => 'Guamo', 'department_id' => 30]);
        City::create(['name' => 'Herveo', 'department_id' => 30]);
        City::create(['name' => 'Honda', 'department_id' => 30]);
        City::create(['name' => 'Icononzo', 'department_id' => 30]);
        City::create(['name' => 'Lerida', 'department_id' => 30]);
        City::create(['name' => 'Líbano', 'department_id' => 30]);
        City::create(['name' => 'Mariquita', 'department_id' => 30]);
        City::create(['name' => 'Melgar', 'department_id' => 30]);
        City::create(['name' => 'Murillo', 'department_id' => 30]);
        City::create(['name' => 'Natagaima', 'department_id' => 30]);
        City::create(['name' => 'Ortega', 'department_id' => 30]);
        City::create(['name' => 'Palocabildo', 'department_id' => 30]);
        City::create(['name' => 'Piedras', 'department_id' => 30]);
        City::create(['name' => 'Planadas', 'department_id' => 30]);
        City::create(['name' => 'Prado', 'department_id' => 30]);
        City::create(['name' => 'Purificacion', 'department_id' => 30]);
        City::create(['name' => 'Rioblanco', 'department_id' => 30]);
        City::create(['name' => 'Roncesvalles', 'department_id' => 30]);
        City::create(['name' => 'Rovira', 'department_id' => 30]);
        City::create(['name' => 'Saldaña', 'department_id' => 30]);
        City::create(['name' => 'San antonio', 'department_id' => 30]);
        City::create(['name' => 'San luis', 'department_id' => 30]);
        City::create(['name' => 'Santa isabel', 'department_id' => 30]);
        City::create(['name' => 'Suarez', 'department_id' => 30]);
        City::create(['name' => 'Valle de san juan', 'department_id' => 30]);
        City::create(['name' => 'Venadillo', 'department_id' => 30]);
        City::create(['name' => 'Villahermosa', 'department_id' => 30]);
        City::create(['name' => 'Villarrica', 'department_id' => 30]);

        City::create(['name' => 'Cali', 'department_id' => 31]);
        City::create(['name' => 'Alcala', 'department_id' => 31]);
        City::create(['name' => 'Andalucia', 'department_id' => 31]);
        City::create(['name' => 'Ansermanuevo', 'department_id' => 31]);
        City::create(['name' => 'Argelia', 'department_id' => 31]);
        City::create(['name' => 'Bolivar', 'department_id' => 31]);
        City::create(['name' => 'Buenaventura', 'department_id' => 31]);
        City::create(['name' => 'Guadalajara de buga', 'department_id' => 31]);
        City::create(['name' => 'Bugalagrande', 'department_id' => 31]);
        City::create(['name' => 'Caicedonia', 'department_id' => 31]);
        City::create(['name' => 'Calima', 'department_id' => 31]);
        City::create(['name' => 'Candelaria', 'department_id' => 31]);
        City::create(['name' => 'Cartago', 'department_id' => 31]);
        City::create(['name' => 'Dagua', 'department_id' => 31]);
        City::create(['name' => 'El aguila', 'department_id' => 31]);
        City::create(['name' => 'El cairo', 'department_id' => 31]);
        City::create(['name' => 'El cerrito', 'department_id' => 31]);
        City::create(['name' => 'El dovio', 'department_id' => 31]);
        City::create(['name' => 'Florida', 'department_id' => 31]);
        City::create(['name' => 'Ginebra', 'department_id' => 31]);
        City::create(['name' => 'Guacari', 'department_id' => 31]);
        City::create(['name' => 'Jamundi', 'department_id' => 31]);
        City::create(['name' => 'La cumbre', 'department_id' => 31]);
        City::create(['name' => 'La union', 'department_id' => 31]);
        City::create(['name' => 'La victoria', 'department_id' => 31]);
        City::create(['name' => 'Obando', 'department_id' => 31]);
        City::create(['name' => 'Palmira', 'department_id' => 31]);
        City::create(['name' => 'Pradera', 'department_id' => 31]);
        City::create(['name' => 'Restrepo', 'department_id' => 31]);
        City::create(['name' => 'Riofrio', 'department_id' => 31]);
        City::create(['name' => 'Roldanillo', 'department_id' => 31]);
        City::create(['name' => 'San pedro', 'department_id' => 31]);
        City::create(['name' => 'Sevilla', 'department_id' => 31]);
        City::create(['name' => 'Toro', 'department_id' => 31]);
        City::create(['name' => 'Trujillo', 'department_id' => 31]);
        City::create(['name' => 'Tulua', 'department_id' => 31]);
        City::create(['name' => 'Ulloa', 'department_id' => 31]);
        City::create(['name' => 'Versalles', 'department_id' => 31]);
        City::create(['name' => 'Vijes', 'department_id' => 31]);
        City::create(['name' => 'Yotoco', 'department_id' => 31]);
        City::create(['name' => 'Yumbo', 'department_id' => 31]);
        City::create(['name' => 'Zarzal', 'department_id' => 31]);

        City::create(['name' => 'Mitú', 'department_id' => 32]);
        City::create(['name' => 'Caruru', 'department_id' => 32]);
        City::create(['name' => 'Pacoa', 'department_id' => 32]);
        City::create(['name' => 'Taraira', 'department_id' => 32]);
        City::create(['name' => 'Papunaua', 'department_id' => 32]);
        City::create(['name' => 'Yavarate', 'department_id' => 32]);

        City::create(['name' => 'Puerto carreño', 'department_id' => 33]);
        City::create(['name' => 'La primavera', 'department_id' => 33]);
        City::create(['name' => 'Santa rosalia', 'department_id' => 33]);
        City::create(['name' => 'Cumaribo', 'department_id' => 33]);
    }
}
